/** Mọi chuỗi hiển thị nằm ở đây. Thêm ngôn ngữ: thêm một bảng cùng hình dạng. */
export const strings = {
  title: ['Pacific', 'Ash'] as [string, string],
  menu: { play: 'Chơi', armory: 'Khí tài', settings: 'Cài đặt' },
  common: { back: 'Quay lại', continue: 'Tiếp tục', close: 'Đóng', cancel: 'Hủy', locked: 'Sắp có', you: 'Bạn', enemy: 'Địch', opponent: 'Đối thủ' },
  mode: {
    title: 'Chọn chế độ',
    pve: { name: 'PvE vs AI', desc: 'Đấu với máy. Chọn độ khó.' },
    hotseat: { name: 'Hot-seat', desc: 'Hai người chung một máy, chuyền tay nhau.' },
    online: { name: 'Online', desc: 'Đấu qua mạng: mời bạn bằng mã phòng hoặc link, hoặc ghép ngẫu nhiên.' },
    start: 'Vào trận',
    turnLimit: 'Giới hạn thời gian mỗi lượt', turnLimitDesc: 'Hết giờ, hệ thống tự bắn một phát ngẫu nhiên hợp lệ thay bạn. Online: người tạo phòng quyết định.', noLimit: 'Không giới hạn',
    equip: 'Hỏng hóc khí tài', equipDesc: 'Tàu bị trúng quá 50% số ô mất kỹ năng đặc biệt: tàu có đòn chỉ còn bắn 1 ô, tàu nội tại mất tác dụng.',
    difficulty: { easy: 'Dễ', medium: 'Vừa', hard: 'Khó' },
  },
  online: {
    title: 'Online', create: 'Tạo phòng', createDesc: 'Tạo phòng riêng, gửi mã hoặc link cho bạn bè.',
    join: 'Vào phòng', joinDesc: 'Nhập mã phòng bạn bè gửi.', quick: 'Ghép ngẫu nhiên', quickDesc: 'Tìm một người chơi khác đang chờ cùng lúc.',
    roomCode: 'Mã phòng', inviteLink: 'Link mời', copy: 'Sao chép link', copied: 'Đã sao chép link.', waitingFriend: 'Chờ người chơi khác vào phòng…',
    searching: 'Đang tìm đối thủ…', connecting: 'Đang kết nối máy chủ…', lost: 'Mất kết nối máy chủ.', needCode: 'Nhập đủ 5 ký tự mã phòng.',
    cannotConnect: (url: string) => `Không kết nối được máy chủ ${url}. Kiểm tra địa chỉ máy chủ ở mục bên dưới.`,
    server: 'Máy chủ', serverHint: 'Địa chỉ WebSocket của máy chủ online (ví dụ ws://localhost:8787 hoặc wss://ten-mien).',
    waitingOpponent: 'Đã chốt đội hình. Chờ đối thủ xếp tàu…', opponentLeft: 'Đối thủ đã thoát. Bạn thắng.', opponentLeftPlacing: 'Đối thủ đã thoát khi xếp tàu.',
    limitInfo: (s: number) => (s ? `Giới hạn mỗi lượt: ${s} giây (đổi ở màn chọn chế độ).` : 'Không giới hạn thời gian mỗi lượt (đổi ở màn chọn chế độ).'),
    resumeFailed: 'Không nối lại được trận cũ (phòng đã đóng).', reconnecting: 'Mất kết nối, đang nối lại…', foeDropped: (s: number) => `Đối thủ mất kết nối, chờ tối đa ${s} giây…`, foeBack: 'Đối thủ đã nối lại.', backOnline: 'Đã nối lại.',
    room: (c: string) => `Phòng ${c}`, foeThinking: 'Đối thủ đang nhắm…', rematch: 'Về sảnh online',
  },
  hangar: {
    title: 'Khí tài',
    profiles: 'Profile', newProfile: 'Tạo profile', empty: 'Chưa có profile nào. Tạo một profile để gắn tàu.',
    name: 'Tên profile', rename: 'Đổi tên', remove: 'Xóa profile', removeConfirm: 'Chắc chắn? Chạm lần nữa',
    shipsIn: (n: number, max: number) => `Tàu trong profile (${n}/${max})`, noShips: 'Chưa gắn tàu nào.',
    allShips: 'Tất cả tàu', add: 'Gắn vào profile', drop: 'Bỏ khỏi profile', full: 'Profile đã đủ tàu',
    selectProfile: 'Chọn một profile để gắn tàu.',
    favorite: 'Yêu thích', unfavorite: 'Bỏ yêu thích',
    count: (n: number) => `${n} tàu`,
    size: 'Kích thước', cooldown: 'Hồi chiêu', attack: 'Đòn đánh', pattern: 'Vùng đánh',
    cells: 'ô', turns: 'lượt', ready: 'Bắn mỗi lượt',
    preview: 'Xem thử đòn đánh',
    noRotate: 'không xoay', passiveTag: 'NỘI TẠI (tự kích hoạt)',
    patternNote: {
      rapid: 'Hai ô bất kỳ (ví dụ)', precision: 'Một ô', torpedo: 'Cả hàng hoặc cột, từ mép lưới',
      cross: 'Chữ thập 5 ô', line3: 'Dải 4 ô, ngang hoặc dọc', barrage: '5 ô ngẫu nhiên chưa bắn, không cần nhắm',
      sneak: 'Bắn 1 ô ngẫu nhiên chưa bắn, đầu trận và cách một lượt', guard: 'Triệt tiêu 30% ô của mỗi đòn địch, cách một đòn',
    } as Record<string, string>,
  },
  placement: {
    title: 'Đặt tàu', random: 'Ngẫu nhiên', rotate: 'Xoay (R)', reset: 'Đặt lại', confirm: 'Xác nhận',
    tray: (n: number, total: number) => `Tàu chưa đặt (${n}/${total})`, allPlaced: 'Đã đặt xong các tàu mang theo',
    hint: 'Chọn tàu mang theo (tối đa 5 trong 8), rồi kéo tàu vào lưới hoặc chạm tàu rồi chạm ô. Con trỏ nằm giữa tàu (tàu hộ vệ: góc trên-trái, không xoay). Kéo tàu ra ngoài lưới để gỡ.',
    player: (n: number) => `Người chơi ${n}`,
    viewAll: 'Tất cả tàu', viewProfile: 'Theo profile',
    bring: (n: number, max: number) => `Mang theo ${n}/${max}`,
    take: 'Mang theo', leave: 'Bỏ', use: 'Dùng', using: 'Đang dùng', maxReached: 'Đã đủ 5 tàu',
    emptyProfile: 'Profile chưa có tàu.', noProfiles: 'Chưa có profile. Tạo ở mục Khí tài.',
    needOne: 'Chọn ít nhất 1 tàu.', needActive: 'Cần ít nhất một tàu có đòn đánh (không chỉ cắn lén/hộ vệ).',
  },
  pass: {
    title: (n: number) => `Chuyển máy cho Người chơi ${n}`,
    sub: 'Che màn hình để không lộ lưới.',
    button: (n: number) => `Tôi là Người chơi ${n}`,
  },
  battle: {
    turn: (n: number) => `Lượt ${n}`,
    yours: 'Của bạn', theirs: 'Đối thủ', thinking: 'Đối thủ đang nhắm…',
    player: (n: number) => `Người chơi ${n}`,
    fleet: 'Đội của bạn', enemyFleet: 'Hạm đội địch', logTitle: 'Nhật ký', emptyLog: 'Chưa có lượt nào.',
    enemyGrid: 'Lưới địch', ownGrid: 'Lưới của bạn',
    fire: 'Bắn', rotate: 'Xoay (R)', skip: 'Bỏ qua', speed: 'Tốc độ', cancel: 'Hủy chọn',
    selectedShip: 'Tàu đang chọn',
    pickShip: 'Chọn một tàu sẵn sàng ở danh sách.',
    waiting: 'Chờ lượt đối thủ.',
    ready: 'Sẵn sàng', selecting: 'Đang chọn', cooldown: (n: number) => `Hồi chiêu ${n}`,
    sunk: 'Chìm', revealed: 'Đã lộ', unknown: 'Chưa rõ',
    cdAfter: (n: number) => (n === 0 ? 'Bắn được mỗi lượt.' : `Hồi chiêu sau khi bắn: ${n} lượt.`),
    toastSunkEnemy: (name: string) => `Đã đánh chìm: ${name}`,
    toastSunkOwn: (name: string) => `Tàu của bạn bị chìm: ${name}`,
    toastSkip: 'Không có tàu sẵn sàng, bỏ lượt',
    brokenAtk: 'Hỏng khí tài: bắn 1 ô', brokenTag: 'Hỏng khí tài', brokenPassive: 'Hỏng · mất tác dụng',
    brokenDesc: 'Bị trúng quá 50% số ô: mất kỹ năng đặc biệt, chỉ còn bắn 1 ô, không kèm hiệu ứng.',
    toastBroken: (name: string) => `Hỏng khí tài: ${name} mất kỹ năng đặc biệt`,
    viewTitle: 'Chuyển 2D / 3D (V)', hint3d: 'Kéo để xoay 360°, kéo chuột phải / giữ Shift / WASD để dời sang lưới khác, cuộn để zoom, chạm ô lưới địch để nhắm.',
    focusTitle: 'Dời camera 3D: giữa trận / lưới địch / lưới mình (F)', focus: { center: 'GIỮA', enemy: 'LƯỚI ĐỊCH', own: 'LƯỚI TA' },
    timeUp: 'Hết giờ: tự động bắn.',
    passive: 'NỘI TẠI', sneakRest: 'Nghỉ 1 lượt', sneakNext: 'Bắn ở lượt tới', guardReady: 'Sẵn sàng chặn', guardRest: 'Nghỉ 1 đòn',
    toastSneakOwn: 'Tàu cắn lén của bạn bắn lén!', toastSneakFoe: 'Địch phục kích!',
    toastGuardOwn: (n: number) => `Hộ vệ triệt tiêu ${n} ô đòn của địch`, toastGuardFoe: (n: number) => `Hộ vệ địch chặn ${n} ô: có tàu hộ vệ ở đây`,
    toastRevealed: (name: string) => `Lộ loại tàu: ${name}`,
    hint: {
      rapid: (n: number) => `Chọn 2 ô (đã chọn ${n}/2).`,
      precision: 'Chạm một ô để nhắm.',
      torpedo: 'Chạm số hàng hoặc chữ cột ở mép lưới. Chạm lại để đổi phía.',
      cross: 'Chạm một ô để chọn tâm.',
      line3: 'Chạm một ô để chọn tâm, nhấn Xoay để đổi hướng.',
      barrage: '5 Ô NGẪU NHIÊN: không cần nhắm, bấm BẮN.',
    },
    cellState: { miss: 'trượt', hit: 'trúng', sunk: 'chìm', unknown: 'chưa bắn', blocked: 'bị hộ vệ chặn' },
    side: { you: 'BẠN', foe: 'ĐỊCH', opponent: 'ĐỐI THỦ' },
    log: {
      miss: 'trượt',
      hits: (n: number) => `${n} trúng`,
      sunkEnemy: (name: string) => `${name} địch CHÌM`,
      sunkOwn: (name: string) => `${name} của bạn CHÌM`,
      revealed: (name: string) => `lộ ${name}`,
      skipped: 'bỏ lượt (không có tàu sẵn sàng)',
      sneak: 'cắn lén',
      blocked: (n: number) => `hộ vệ chặn ${n} ô`,
      ended: 'Kết thúc ván',
      row: (n: number) => `hàng ${n}`,
      col: (c: string) => `cột ${c}`,
    },
    quit: 'Bỏ cuộc, về menu', quitConfirm: 'Chắc chắn? Chạm lần nữa',
  },
  result: {
    win: 'Chiến thắng', lose: 'Thất bại',
    winner: (n: number) => `Người chơi ${n} thắng`,
    stats: 'Thống kê', turns: 'Số lượt', hits: 'Trúng', misses: 'Trượt', accuracy: 'Tỉ lệ trúng', alive: 'Tàu còn sống',
    again: 'Chơi lại', againOnline: 'Về sảnh online', menu: 'Về menu',
  },
  settings: {
    title: 'Cài đặt',
    master: 'Âm lượng tổng', sfx: 'Hiệu ứng', music: 'Nhạc',
    quality: 'Chất lượng đồ họa', low: 'Thấp', medium: 'Trung', high: 'Cao',
    anim: 'Tốc độ animation', off: 'Tắt', x1: 'x1', x2: 'x2',
    shake: 'Rung màn hình', shortCine: 'Cinematic ngắn', cineBars: 'Khung điện ảnh', glare: 'Độ chói hiệu ứng', sinkBg: 'Tàu chìm chạy nền',
    map: 'Chọn map', mapNote: 'Chọn là đổi ngay: cảnh nền phía sau mờ chuyển trong 600 ms.',
    mapLoadFail: 'Không tải được map',
  },
  map: {
    truong_sa: { name: 'Trường Sa', desc: 'Hoàng hôn, quần đảo cháy, nhiều tàu bắn tên lửa qua nhau' },
    hai_phong: { name: 'Hải Phòng hoang tàn', desc: 'Mưa lớn, thành phố cảng cháy dở, ánh cam lạnh' },
  },
  arena: {
    name: 'Hải chiến', desc: 'Lái một chiến hạm góc nhìn thứ ba, ngắm bắn góc nhìn thứ nhất. Tối đa 6 tàu, đánh đơn hoặc chia đội.',
    lobbyTitle: 'Hải chiến — Sảnh', you: 'Bạn', bot: 'Máy', empty: 'Trống', random: 'Ngẫu nhiên', team: 'Đội', design: 'Thiết kế',
    modes: { ffa: 'Mỗi người một đội', t2: '2 đội', t3: '3 đội' } as Record<string, string>, mode: 'Kiểu trận', level: 'Độ khó của máy',
    start: 'Ra khơi', needFoe: 'Cần ít nhất 2 đội khác nhau.', players: (n: number) => `${n}/6 tàu`,
    online: 'Hải chiến chơi mạng tối đa 6 người; chỗ trống có thể để máy lấp.',
    tabs: { tactic: 'Chiến thuật', arena: 'Hải chiến' }, tabTactic: 'Bắn tàu theo lượt trên lưới 10×10', tabArena: 'Lái chiến hạm, ngắm bắn góc nhìn thứ nhất, tối đa 6 tàu',
    arenaCard: 'Vào sảnh Hải chiến', kindQueue: 'Ghép trận online', kindCustom: 'Custom nội bộ', kindLabel: 'Kiểu chơi',
    queueDesc: 'Vào hàng chờ công khai: ghép với người chơi khác, tự bắt đầu sau đếm ngược khi có từ 2 người (đủ 6 thì vào ngay). Mỗi người một đội.',
    findMatch: 'Tìm trận', searching: 'Đang tìm trận…', myName: 'Tên hiển thị', mySetup: 'Tàu của bạn',
    invite: 'Mời bạn chơi online', inviteDesc: 'Tạo phòng mang theo cấu hình hiện tại (máy, đội, độ khó). Gửi link hoặc mã phòng cho bạn bè; họ vào thay chỗ máy.', inviteBtn: 'Tạo phòng & mời', joinCode: 'Vào bằng mã phòng', joinBtn: 'Vào phòng',
    localStart: 'Ra khơi (nội bộ)', connecting: 'Đang kết nối máy chủ…', connectFail: 'Không kết nối được máy chủ.',
    roomTitle: (c: string) => `Phòng ${c}`, publicRoom: 'Ghép trận công khai', host: 'Chủ phòng', roomCode: 'Mã phòng', link: 'Link mời', copy: 'Chép link', copied: 'Đã chép link.',
    addBot: '＋ Thêm máy', removeBot: 'Gỡ', startMatch: 'Bắt đầu trận', waitHost: 'Chờ chủ phòng bắt đầu…', countdown: (s: number) => `Trận bắt đầu sau ${s} giây`, needTwo: 'Chờ thêm người (cần từ 2 người).',
    leaveRoom: 'Rời phòng', privateRoom: 'Phòng riêng', localRoom: 'Phòng nội bộ', seats: 'Chỗ ngồi', queueNote: 'Ghép trận công khai: không thêm máy, mỗi người một đội, tự bắt đầu sau đếm ngược.', localNote: 'Không nối được máy chủ: phòng nội bộ trên máy này (chỉ chơi với máy, chưa mời được bạn).', localNoLink: 'Cần máy chủ để có link mời', closed: 'Phòng đã đóng hoặc mất kết nối.', backRoom: 'Về phòng', joinFail: 'Không vào được phòng.', teamNames: ['Xanh', 'Cam', 'Lục', 'Tím', 'Vàng', 'Đỏ'],
    yardTab: 'Chế tạo tàu', fleetTab: 'Hạm đội (Battleship)', yardTitle: 'Xưởng đóng tàu', designs: 'Thiết kế của bạn', newDesign: 'Tạo thiết kế', dup: 'Nhân bản', del: 'Xóa', delConfirm: 'Chắc chắn? Chạm lần nữa',
    hull: 'Thân tàu', slots: 'Chỗ gắn khí tài', weapons: 'Khí tài', clear: 'Gỡ', emptySlot: '— Trống —', size: 'Cỡ',
    nameLabel: 'Tên thiết kế', sizeNames: ['', 'Nhẹ', 'Vừa', 'Nặng'],
    stat: { hp: 'Độ bền', speed: 'Tốc độ', turn: 'Quay đầu', weight: 'Tải trọng', armed: 'Khí tài' },
    wstat: { dmg: 'Sát thương', range: 'Tầm', reload: 'Nạp', mag: 'Băng', splash: 'Nổ lan', speed: 'Vận tốc đạn' },
    view: { hint: 'Kéo: xoay 360° · Lăn: zoom · Bấm số trên tàu: chọn chỗ gắn', all: 'Toàn tàu', spin: 'Tự xoay', slot: 'Chỗ gắn', arc: 'Cung bắn', full: 'Quay 360°', emptyInfo: 'Chỗ trống — chọn khí tài bên phải để gắn.', maxSize: 'Cỡ tối đa', aim: 'Xoay ngang', elev: 'Ngẩng nòng', ammo: 'Băng đạn', perSalvo: 'phát', speedU: 'đv/s', noElev: 'cố định (chỉ xoay ngang)' },
    hullHint: 'Chọn cỡ thân. Mỗi khí tài nặng làm tàu chậm đi một chút.', fits: 'Lắp được', tooBig: 'Quá cỡ chỗ gắn',
    hud: {
      hull: 'Thân tàu', speed: 'Tốc độ', throttle: 'Cần ga', rudder: 'Bánh lái', reload: 'Đang nạp', ready: 'Sẵn sàng', aimBearing: 'Hướng', aimElev: 'Góc ngẩng', aimRange: 'Điểm rơi', aimTime: 'Bay',
      driveHelp: 'W/S: ga · A/D: bánh lái · 1–7 hoặc Q/E: cầm khí tài · chuột phải kéo: xoay camera · lăn: zoom · T: đường đạn',
      weaponHelp: 'Di chuột: xoay/ngẩng nòng · chuột trái hoặc SPACE: bắn · W/S/A/D: tinh chỉnh · X/Esc: thoát khí tài',
      pause: 'Tạm dừng', resume: 'Tiếp tục', leave: 'Về sảnh', outside: 'RỜI VÙNG CHIẾN SỰ — quay vào!', spectate: 'Bạn đã chìm — đang xem', specHint: 'Q/E: đổi tàu xem',
      win: 'CHIẾN THẮNG', lose: 'THẤT BẠI', draw: 'HÒA', again: 'Chơi lại', score: 'Bảng điểm', kills: 'Hạ', dmg: 'Sát thương', alive: 'Còn', sunk: 'Chìm',
    },
  },
  soon: 'Đang phát triển',
};
