/** Mọi chuỗi hiển thị nằm ở đây. Thêm ngôn ngữ: thêm một bảng cùng hình dạng. */
export const strings = {
  title: ['Pacific', 'Ash'] as [string, string],
  menu: { play: 'Chơi', armory: 'Khí tài', settings: 'Cài đặt' },
  common: { back: 'Quay lại', continue: 'Tiếp tục', close: 'Đóng', cancel: 'Hủy', locked: 'Sắp có', you: 'Bạn', enemy: 'Địch', opponent: 'Đối thủ' },
  mode: {
    title: 'Chọn chế độ',
    pve: { name: 'PvE vs AI', desc: 'Đấu với máy. Chọn độ khó.' },
    hotseat: { name: 'Hot-seat', desc: 'Hai người chung một máy, chuyền tay nhau.' },
    online: { name: 'Online', desc: 'Đấu qua mạng: mời bạn bằng mã phòng hoặc link, hoặc ghép ngẫu nhiên.' },
    start: 'Vào trận',
    turnLimit: 'Giới hạn thời gian mỗi lượt', turnLimitDesc: 'Hết giờ, hệ thống tự bắn một phát ngẫu nhiên hợp lệ thay bạn. Online: người tạo phòng quyết định.', noLimit: 'Không giới hạn',
    equip: 'Hỏng hóc khí tài', equipDesc: 'Tàu bị trúng quá 50% số ô mất kỹ năng đặc biệt: tàu có đòn chỉ còn bắn 1 ô, tàu nội tại mất tác dụng.',
    difficulty: { easy: 'Dễ', medium: 'Vừa', hard: 'Khó' },
  },
  online: {
    title: 'Online', create: 'Tạo phòng', createDesc: 'Tạo phòng riêng, gửi mã hoặc link cho bạn bè.',
    join: 'Vào phòng', joinDesc: 'Nhập mã phòng bạn bè gửi.', quick: 'Ghép ngẫu nhiên', quickDesc: 'Tìm một người chơi khác đang chờ cùng lúc.',
    roomCode: 'Mã phòng', inviteLink: 'Link mời', copy: 'Sao chép link', copied: 'Đã sao chép link.', waitingFriend: 'Chờ người chơi khác vào phòng…',
    searching: 'Đang tìm đối thủ…', connecting: 'Đang kết nối máy chủ…', lost: 'Mất kết nối máy chủ.', needCode: 'Nhập đủ 5 ký tự mã phòng.',
    cannotConnect: (url: string) => `Không kết nối được máy chủ ${url}. Kiểm tra địa chỉ máy chủ ở mục bên dưới.`,
    server: 'Máy chủ', serverHint: 'Địa chỉ WebSocket của máy chủ online (ví dụ ws://localhost:8787 hoặc wss://ten-mien).',
    waitingOpponent: 'Đã chốt đội hình. Chờ đối thủ xếp tàu…', opponentLeft: 'Đối thủ đã thoát. Bạn thắng.', opponentLeftPlacing: 'Đối thủ đã thoát khi xếp tàu.',
    limitInfo: (s: number) => (s ? `Giới hạn mỗi lượt: ${s} giây (đổi ở màn chọn chế độ).` : 'Không giới hạn thời gian mỗi lượt (đổi ở màn chọn chế độ).'),
    resumeFailed: 'Không nối lại được trận cũ (phòng đã đóng).', reconnecting: 'Mất kết nối, đang nối lại…', foeDropped: (s: number) => `Đối thủ mất kết nối, chờ tối đa ${s} giây…`, foeBack: 'Đối thủ đã nối lại.', backOnline: 'Đã nối lại.',
    room: (c: string) => `Phòng ${c}`, foeThinking: 'Đối thủ đang nhắm…', rematch: 'Về sảnh online',
  },
  hangar: {
    title: 'Khí tài',
    profiles: 'Profile', newProfile: 'Tạo profile', empty: 'Chưa có profile nào. Tạo một profile để gắn tàu.',
    name: 'Tên profile', rename: 'Đổi tên', remove: 'Xóa profile', removeConfirm: 'Chắc chắn? Chạm lần nữa',
    shipsIn: (n: number, max: number) => `Tàu trong profile (${n}/${max})`, noShips: 'Chưa gắn tàu nào.',
    allShips: 'Tất cả tàu', add: 'Gắn vào profile', drop: 'Bỏ khỏi profile', full: 'Profile đã đủ tàu',
    selectProfile: 'Chọn một profile để gắn tàu.',
    favorite: 'Yêu thích', unfavorite: 'Bỏ yêu thích',
    count: (n: number) => `${n} tàu`,
    size: 'Kích thước', cooldown: 'Hồi chiêu', attack: 'Đòn đánh', pattern: 'Vùng đánh',
    cells: 'ô', turns: 'lượt', ready: 'Bắn mỗi lượt',
    preview: 'Xem thử đòn đánh',
    noRotate: 'không xoay', passiveTag: 'NỘI TẠI (tự kích hoạt)',
    patternNote: {
      rapid: 'Hai ô bất kỳ (ví dụ)', precision: 'Một ô', torpedo: 'Cả hàng hoặc cột, từ mép lưới',
      cross: 'Chữ thập 5 ô', line3: 'Dải 3 ô, ngang hoặc dọc',
      sneak: 'Bắn 1 ô ngẫu nhiên chưa bắn, đầu trận và cách một lượt', guard: 'Triệt tiêu 30% ô của mỗi đòn địch, cách một đòn',
    } as Record<string, string>,
  },
  placement: {
    title: 'Đặt tàu', random: 'Ngẫu nhiên', rotate: 'Xoay (R)', reset: 'Đặt lại', confirm: 'Xác nhận',
    tray: (n: number, total: number) => `Tàu chưa đặt (${n}/${total})`, allPlaced: 'Đã đặt xong các tàu mang theo',
    hint: 'Chọn tàu mang theo (tối đa 5 trong 7), rồi kéo tàu vào lưới hoặc chạm tàu rồi chạm ô. Con trỏ nằm giữa tàu (tàu hộ vệ: góc trên-trái, không xoay). Kéo tàu ra ngoài lưới để gỡ.',
    player: (n: number) => `Người chơi ${n}`,
    viewAll: 'Tất cả tàu', viewProfile: 'Theo profile',
    bring: (n: number, max: number) => `Mang theo ${n}/${max}`,
    take: 'Mang theo', leave: 'Bỏ', use: 'Dùng', using: 'Đang dùng', maxReached: 'Đã đủ 5 tàu',
    emptyProfile: 'Profile chưa có tàu.', noProfiles: 'Chưa có profile. Tạo ở mục Khí tài.',
    needOne: 'Chọn ít nhất 1 tàu.', needActive: 'Cần ít nhất một tàu có đòn đánh (không chỉ cắn lén/hộ vệ).',
  },
  pass: {
    title: (n: number) => `Chuyển máy cho Người chơi ${n}`,
    sub: 'Che màn hình để không lộ lưới.',
    button: (n: number) => `Tôi là Người chơi ${n}`,
  },
  battle: {
    turn: (n: number) => `Lượt ${n}`,
    yours: 'Của bạn', theirs: 'Đối thủ', thinking: 'Đối thủ đang nhắm…',
    player: (n: number) => `Người chơi ${n}`,
    fleet: 'Đội của bạn', enemyFleet: 'Hạm đội địch', logTitle: 'Nhật ký', emptyLog: 'Chưa có lượt nào.',
    enemyGrid: 'Lưới địch', ownGrid: 'Lưới của bạn',
    fire: 'Bắn', rotate: 'Xoay (R)', skip: 'Bỏ qua', speed: 'Tốc độ', cancel: 'Hủy chọn',
    selectedShip: 'Tàu đang chọn',
    pickShip: 'Chọn một tàu sẵn sàng ở danh sách.',
    waiting: 'Chờ lượt đối thủ.',
    ready: 'Sẵn sàng', selecting: 'Đang chọn', cooldown: (n: number) => `Hồi chiêu ${n}`,
    sunk: 'Chìm', revealed: 'Đã lộ', unknown: 'Chưa rõ',
    cdAfter: (n: number) => (n === 0 ? 'Bắn được mỗi lượt.' : `Hồi chiêu sau khi bắn: ${n} lượt.`),
    toastSunkEnemy: (name: string) => `Đã đánh chìm: ${name}`,
    toastSunkOwn: (name: string) => `Tàu của bạn bị chìm: ${name}`,
    toastSkip: 'Không có tàu sẵn sàng, bỏ lượt',
    brokenAtk: 'Hỏng khí tài: bắn 1 ô', brokenTag: 'Hỏng khí tài', brokenPassive: 'Hỏng · mất tác dụng',
    brokenDesc: 'Bị trúng quá 50% số ô: mất kỹ năng đặc biệt, chỉ còn bắn 1 ô, không kèm hiệu ứng.',
    toastBroken: (name: string) => `Hỏng khí tài: ${name} mất kỹ năng đặc biệt`,
    viewTitle: 'Chuyển 2D / 3D (V)', hint3d: 'Kéo để xoay 360°, cuộn để zoom, chạm ô lưới địch để nhắm.',
    timeUp: 'Hết giờ: tự động bắn.',
    passive: 'NỘI TẠI', sneakRest: 'Nghỉ 1 lượt', sneakNext: 'Bắn ở lượt tới', guardReady: 'Sẵn sàng chặn', guardRest: 'Nghỉ 1 đòn',
    toastSneakOwn: 'Tàu cắn lén của bạn bắn lén!', toastSneakFoe: 'Địch phục kích!',
    toastGuardOwn: (n: number) => `Hộ vệ triệt tiêu ${n} ô đòn của địch`, toastGuardFoe: (n: number) => `Hộ vệ địch chặn ${n} ô: có tàu hộ vệ ở đây`,
    toastRevealed: (name: string) => `Lộ loại tàu: ${name}`,
    hint: {
      rapid: (n: number) => `Chọn 2 ô (đã chọn ${n}/2).`,
      precision: 'Chạm một ô để nhắm.',
      torpedo: 'Chạm số hàng hoặc chữ cột ở mép lưới. Chạm lại để đổi phía.',
      cross: 'Chạm một ô để chọn tâm.',
      line3: 'Chạm một ô để chọn tâm, nhấn Xoay để đổi hướng.',
    },
    cellState: { miss: 'trượt', hit: 'trúng', sunk: 'chìm', unknown: 'chưa bắn', blocked: 'bị hộ vệ chặn' },
    side: { you: 'BẠN', foe: 'ĐỊCH', opponent: 'ĐỐI THỦ' },
    log: {
      miss: 'trượt',
      hits: (n: number) => `${n} trúng`,
      sunkEnemy: (name: string) => `${name} địch CHÌM`,
      sunkOwn: (name: string) => `${name} của bạn CHÌM`,
      revealed: (name: string) => `lộ ${name}`,
      skipped: 'bỏ lượt (không có tàu sẵn sàng)',
      sneak: 'cắn lén',
      blocked: (n: number) => `hộ vệ chặn ${n} ô`,
      ended: 'Kết thúc ván',
      row: (n: number) => `hàng ${n}`,
      col: (c: string) => `cột ${c}`,
    },
    quit: 'Bỏ cuộc, về menu', quitConfirm: 'Chắc chắn? Chạm lần nữa',
  },
  result: {
    win: 'Chiến thắng', lose: 'Thất bại',
    winner: (n: number) => `Người chơi ${n} thắng`,
    stats: 'Thống kê', turns: 'Số lượt', hits: 'Trúng', misses: 'Trượt', accuracy: 'Tỉ lệ trúng', alive: 'Tàu còn sống',
    again: 'Chơi lại', againOnline: 'Về sảnh online', menu: 'Về menu',
  },
  settings: {
    title: 'Cài đặt',
    master: 'Âm lượng tổng', sfx: 'Hiệu ứng', music: 'Nhạc',
    quality: 'Chất lượng đồ họa', low: 'Thấp', medium: 'Trung', high: 'Cao',
    anim: 'Tốc độ animation', off: 'Tắt', x1: 'x1', x2: 'x2',
    shake: 'Rung màn hình', shortCine: 'Cinematic ngắn',
    map: 'Chọn map', mapNote: 'Chọn là đổi ngay: cảnh nền phía sau mờ chuyển trong 600 ms.',
    mapLoadFail: 'Không tải được map',
  },
  map: {
    truong_sa: { name: 'Trường Sa', desc: 'Hoàng hôn, quần đảo cháy, nhiều tàu bắn tên lửa qua nhau' },
    hai_phong: { name: 'Hải Phòng hoang tàn', desc: 'Mưa lớn, thành phố cảng cháy dở, ánh cam lạnh' },
  },
  soon: 'Đang phát triển',
};
