// E2E giao diện, xem hướng dẫn chạy ở playthrough.mjs.
import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1200, height: 900 });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
await page.evaluateOnNewDocument(() => localStorage.setItem('pacific-ash.settings', JSON.stringify({ anim: 'off' })));
await page.goto('http://localhost:4599/?no3d');
const click = (s) => page.waitForSelector(s).then(() => page.click(s));
await click('.btn--primary'); await click('[data-level="easy"]'); await click('[data-start="pve"]');
await click('[data-random]'); await click('[data-confirm]');
await page.waitForSelector('.frow:not(:disabled)', { timeout: 8000 });
const E = '.b-enemy ';
const cell = (x, y) => `${E}.g-cell[data-x="${x}"][data-y="${y}"]`;
const fireDisabled = () => page.$eval('[data-fire]', (b) => b.disabled);
const count = (sel) => page.$$eval(sel, (a) => a.length);
const r = {};
await click('.frow[data-ship="destroyer"]');
await click(cell(0, 0)); r.rapid1Disabled = await fireDisabled();
await click(cell(1, 0)); r.rapid2Enabled = !(await fireDisabled());
r.numbers = await page.$$eval(E + '.c--sel use', (a) => a.map((e) => e.getAttribute('href')));
await click(cell(5, 5)); r.rapidThirdResets = (await count(E + '.c--sel')) === 1 && (await fireDisabled());
await page.keyboard.press('Escape'); r.escClearsAim = (await count(E + '.c--sel')) === 0;
await page.keyboard.press('Escape'); r.escDeselects = (await count('.frow[aria-pressed="true"]')) === 0;
await click('.frow[data-ship="submarine"]');
r.handlesOn = await page.$eval(E + '.grid', (g) => g.classList.contains('grid--handles'));
await click(E + '.g-handle[data-hrow="3"]');
r.torpStart = await page.$eval(E + '.g-handle[data-hrow="3"]', (h) => h.classList.contains('h--start'));
r.torpPreview = await count(E + '.c--prev-hostile');
await click(E + '.g-handle[data-hrow="3"]');
r.torpEnd = await page.$eval(E + '.g-handle[data-hrow="3"]', (h) => h.classList.contains('h--end'));
r.torpFireEnabled = !(await fireDisabled());
await click(E + '.g-handle[data-hcol="2"]'); r.colAxis = await count(E + '.c--prev-hostile');
await click('.frow[data-ship="carrier"]');
await click(cell(4, 4)); r.line3h = await count(E + '.c--prev-hostile');
await page.keyboard.press('r');
r.line3v = await page.$$eval(E + '.c--prev-hostile', (a) => new Set(a.map((e) => e.dataset.x)).size === 1);
await click(cell(0, 0)); r.line3EdgeCells = await count(E + '.c--prev-hostile');
await click('.frow[data-ship="missile"]'); await click(cell(9, 9)); r.crossCorner = await count(E + '.c--prev-hostile');
// bắn thật bằng tên lửa, rồi kiểm tra lượt đổi và hồi chiêu hiện
await click('[data-fire]');
await page.waitForFunction(() => document.querySelector('.frow:not(:disabled)') && document.querySelector('.info__hint')?.textContent.includes('Chọn'), { timeout: 8000 });
r.missileCooldownShown = await page.$eval('.frow[data-ship="missile"] .frow__state', (e) => e.textContent);
r.missileDisabled = await page.$eval('.frow[data-ship="missile"]', (b) => b.disabled);
r.logLines = await count('.log li');
r.errors = errs;
console.log(JSON.stringify(r, null, 1));
await browser.close();
